#!/usr/bin/env bash
# Push deploy-bundle/ to the server without destroying server-only state.
#
# `rsync --delete` mirrors the bundle onto the app root, so anything that
# exists ONLY on the server is deleted unless it is excluded here. Two of
# those take the whole site down when they disappear:
#
#   .htaccess  the CloudLinux/Passenger stanza cPanel generates. Without it
#              Apache stops handing requests to Passenger and serves ~/ni3ma
#              as a static directory — no index.html, so visitors get a bare
#              directory index instead of the app.
#   .env       the real secrets (DATABASE_URL, AUTH_SECRET, ROOT_DOMAIN).
#              The bundle only carries .env.example.
#
# Usage:
#   ./scripts/deploy-rsync.sh user@server:~/ni3ma/
#   DEPLOY_TARGET=user@server:~/ni3ma/ ./scripts/deploy-rsync.sh
#   DEPLOY_YES=1 ./scripts/deploy-rsync.sh user@server:~/ni3ma/   # no prompt

set -euo pipefail
cd "$(dirname "$0")/.."

TARGET="${1:-${DEPLOY_TARGET:-}}"
if [ -z "$TARGET" ]; then
  echo "usage: $0 user@server:~/ni3ma/" >&2
  exit 1
fi

BUNDLE="deploy-bundle"
if [ ! -d "$BUNDLE" ]; then
  echo "ERROR: $BUNDLE/ missing — run ./scripts/deploy-local.sh first" >&2
  exit 1
fi
if [ ! -f "$BUNDLE/app.js" ] || [ ! -d "$BUNDLE/node_modules" ]; then
  echo "ERROR: $BUNDLE/ is incomplete (app.js and/or node_modules missing)." >&2
  echo "       Shipping it with --delete would break the site. Re-run deploy-local.sh." >&2
  exit 1
fi

# Server-owned paths that must survive a mirrored deploy.
EXCLUDES=(
  --exclude ".htaccess"        # Passenger stanza, generated by cPanel
  --exclude ".env"             # real secrets; bundle ships .env.example only
  --exclude "restart.txt"
  --exclude "tmp/"             # Passenger's restart + pid dir
  --exclude "backups/"
  --exclude "logs/"
  --exclude "public/uploads/"  # user-uploaded media
  --exclude ".well-known/"     # ACME / cert validation
)

echo "→ Dry run: $BUNDLE/ → $TARGET"
rsync -avn --delete "${EXCLUDES[@]}" "$BUNDLE/" "$TARGET"

if [ "${DEPLOY_YES:-0}" != "1" ]; then
  echo ""
  read -r -p "Apply the changes above for real? [y/N] " reply
  case "$reply" in
    y|Y|yes|YES) ;;
    *) echo "Aborted."; exit 1 ;;
  esac
fi

echo ""
echo "→ Syncing for real"
rsync -avz --delete "${EXCLUDES[@]}" "$BUNDLE/" "$TARGET"

echo ""
echo "✓ Bundle uploaded."
echo "  Now: ssh <server> 'cd ~/ni3ma && ./scripts/deploy-remote.sh'"
